### PR TITLE
Query JSON cache instead of github api

### PR DESCRIPTION
**Pull request by IgorTodorovskiIBM**
* This changes how the z/OS Open Tools releases are processed, from using Github's API to our new JSON cache which is remotely available at "https://zosopentools.github.io/meta/api/zopen_releases.json"
* It also removes the need for the github oauth token in zopen
* Remaining TODOs:
* [x] Support for installing versioned releases
  * [x] Port [onimugara](https://github.com/kkos/oniguruma) and link it to JQ (for regex support) or alter AWK script 
* [x] Add more error checking
```

### CODE REVIEW

**Comment by IgorTodorovskiIBM** [comment]
Questions for @DevonianTeuchter:
* Is there a better place to store the json cache rather than /tmp? Do you have a location for temporary files? We could also store the cache in a known location and periodically update it or do a check to see if the remote timestamp changed since last download.

**Comment by DevonianTeuchter** [comment]
There exists Rootfs/var/cache (and a further subdir "zopen" used already by zopen itself ) which would be suitable perhaps?
Having a similar concept to dnf's  "--refresh" parameter or "apt-get update" which has to be specified to manually update the JSON cache would be an option familiar to non-zos folks already

**Review by DevonianTeuchter — APPROVED** [review]
Overall, looks good to me.
Without the GitHub tokens, the skeleton processing in zopen-init could be simplified to the first heredoc as the time code is generic but needed adding after the ghtoken placeholder.
The progressHandler logic issue is odd, probably worth spawning a new issue and commenting out it's usage currently as lower priority...
Otherwise, the use of the single JSON file with standard port definitions simplifies processing immensely (no port-suffix issues for example) and with jq, removing a lot of the cryptic regex matching of JSON in shell!

**Comment by v1gnesh** [comment]
Could you show an example of how regex will be used here?
There is a chance we can make bump do the regex part..

**Comment by IgorTodorovskiIBM** [comment]
Ok, the latest commits should cover all the variants of `zopen install` and `zopen query`. I've also included a new version of jq which has the oniguruma library for regexp linked into it.

**Review by HarithaIBM — APPROVED** [review]

**Comment by IgorTodorovskiIBM** [comment]
Latest commit adds the --upgradeable option to list which tools have newer releases available

**Pull request merged**
