### PR TITLE
fix for print elapsed time exit issue

### PR DESCRIPTION
**Pull request by HarithaIBM**
This fixes closes - https://github.com/DevonianTeuchter/meta/issues/28

### CODE REVIEW

**Review by IgorTodorovskiIBM — APPROVED** [review]
Looks good to me as `[ ! -z "$xtrc" ] && set -x` is returning non-zero, maybe we can investigate why at a later time.

**Comment by DevonianTeuchter** [comment]
Wonder if there is a difference in the return code from set -x running from bash or sh [since it's a builtin] perhaps?

In any case, is the modified code being driven from printElapsedTime as it still appears to be commented out in common.inc so the change in printVerbose would not be called?  
```
...
printElapsedTime()
{
  printType=$1
  functionName=$2
  startTime=$3
  elapsedTime=$(( $SECONDS - $startTime ))
  elapsedTimeOutput="$functionName completed in $elapsedTime seconds."
#  case $printType in
#    "info")
#      printInfo "$elapsedTimeOutput"
#      ;;
#    "verbose")
#      printVerbose "$elapsedTimeOutput"
#      ;;
#  esac
}
...

```
Would it also be worth adding the explicit return 0 to the printInfo and printWarning functions for consistency and prevent this odd issue?

**Comment by HarithaIBM** [comment]
> Wonder if there is a difference in the return code from set -x running from bash or sh [since it's a builtin] perhaps?
> 
> In any case, is the modified code being driven from printElapsedTime as it still appears to be commented out in common.inc so the change in printVerbose would not be called?
> 
> ```
> ...
> printElapsedTime()
> {
>   printType=$1
>   functionName=$2
>   startTime=$3
>   elapsedTime=$(( $SECONDS - $startTime ))
>   elapsedTimeOutput="$functionName completed in $elapsedTime seconds."
> #  case $printType in
> #    "info")
> #      printInfo "$elapsedTimeOutput"
> #      ;;
> #    "verbose")
> #      printVerbose "$elapsedTimeOutput"
> #      ;;
> #  esac
> }
> ...
> ```
> 
> Would it also be worth adding the explicit return 0 to the printInfo and printWarning functions for consistency and prevent this odd issue?

Yes, added it there as well.

**Comment by HarithaIBM** [comment]
> Looks good to me as `[ ! -z "$xtrc" ] && set -x` is returning non-zero, maybe we can investigate why at a later time.

Yes sure, raised https://github.com/DevonianTeuchter/meta/issues/50 to track it

**Pull request merged**
